version: "3.9"

services:
  app:
    build: .
    container_name: latest
    ports:
      - "4000:4000" # Expose your app on port 3000
    depends_on:
      - redis # Ensure Redis starts before the app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    develop:
      watch:
        - action: sync
          path: .
          target: /code

    # volumes:
    #   - .:/app # Mount current directory to /app in the container

  redis:
    image: redis:alpine # Use the Redis Alpine image
    container_name: redis-server
    ports:
      - "6379:6379" # Expose Redis on the default port
